[package]
name = "actix-web-hello-world"
version = "0.1.0"
authors = ["Nicholas Staples <nicholas.staples@solution-tribute.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
futures = "0.1"
env_logger = "0.5"
bytes = "0.4"
